# Generated by Django 4.2.16 on 2026-04-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Numéro')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(verbose_name='Description courte')),
                ('long_description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('category', models.CharField(max_length=80, verbose_name='Catégorie')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('stack', models.CharField(help_text='ex: HTML,CSS,Django', max_length=200, verbose_name='Technologies (séparées par des virgules)')),
                ('url', models.URLField(blank=True, verbose_name='Lien du projet')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié ?')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'ordering': ['order', '-year'],
            },
        ),
    ]
