# Generated by Django 4.2.16 on 2026-04-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='◈', max_length=10, verbose_name='Icône')),
                ('category', models.CharField(max_length=80, verbose_name='Catégorie')),
                ('name', models.CharField(max_length=120, verbose_name='Nom du service')),
                ('tags', models.CharField(help_text='ex: Moderne,Responsive,Entreprises', max_length=200, verbose_name='Tags (séparés par des virgules)')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=20, verbose_name='Période')),
                ('title', models.CharField(max_length=120, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actuel ?')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Entrée timeline',
                'verbose_name_plural': 'Entrées timeline',
                'ordering': ['order'],
            },
        ),
    ]
